export const projects = [
  {
    title: 'WordPress',
    description: "",
      image: '/images/11.png',
      tags: ['Theme', 'Plugin'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"",
    image: '/images/12.png',
    tags: ['Theme', 'Plugin'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Corporate Site',
    description: "",
      image: '/images/13.png',
      tags: ['Plugin', 'Theme'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'E-Commerce',
    description: "",
    image: '/images/14.png',
    tags: ['Plugin', 'Theme'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'E-Commerce',
    description: "",
    image: '/images/15.png',
    tags: ['Plugin', 'Theme'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'E-Commerce',
    description: "",
    image: '/images/16.png',
    tags: ['Plugin', 'Theme'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Joined Software House', },
  { year: 2020, text: 'Joined Goflare ', },
  { year: 2021, text: 'Still Working in Goflare', },
  { year: 2022, text: 'Still Working in Goflare', },
];